### ISSUE TITLE
Django createsuperuser from Ansible

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ansiblecube#1]
Currently I have to create the Ideascube superuser manually. 
From CLI : ideascube createsuperuser, Django prompt for superuser password.

I need to find a work around to be able to set the password from Ansible.

Here is the Ansible django module : http://docs.ansible.com/ansible/django_manage_module.html

**Comment by vartagg** [comment]
+1

**Comment by fheslouin** [comment]
The ideascube interface ask now to create a user and password. This is done at first connection.
