### ISSUE TITLE
Add server nickname to internet network ssid

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ansiblecube#10]
We see  now that it's very often that we have more than one server up during the setup, so it would be great to avoid ssid conflicts, and thus using the server hostname instead of hardcode Ideasbox, imho.

Of course, when we will be able to change the ssid name from within the ideascube admin UI this would be easier to do, but as default I think having unique ssid still makes sense.

**Comment by fheslouin** [comment]
This has been updated in ansiblecube/roles/hostapd/templates/hostapd.conf.j2
It would be easy then to change the hotspot when the pull request https://github.com/ideascube/ideascube/pull/221 will be done

**Comment by fheslouin** [comment]
done.
