### ISSUE TITLE
Also add hostname.lan to dnsmasq

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ansiblecube#11]
It could be great to connect to the server using their hostname instead of only hard coded "ideasbox.lan" or IP address. When more than one server is connected on the same network, this conflicts.

**Comment by fheslouin** [comment]
This has been updated in ansiblecube/roles/hostapd/templates/hostapd.conf.j2 
It would be easy then to change the hotspot when the pull request https://github.com/ideascube/ideascube/pull/221would be done

**Comment by fheslouin** [comment]
Tested and working, done in https://github.com/ideascube/ansiblecube/blob/master/roles/dnsmasq/templates/dnsmasq.conf.j2
