### ISSUE TITLE
"unable to resolve host" message when using sudo

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ansiblecube#13]
That does not hurt, because apart from the message I don't see any effect (that's here from the beginning), but that should be fixed anyway.
For example:

```
ideasbox@idb-eth-melkadida-583:~$ sudo su
sudo: unable to resolve host idb-eth-melkadida-583
```

Not sure what's going on.

**Comment by yohanboniface** [comment]
OK, this line of `/etc/hosts`:

```
127.0.1.1   debian
```

needs to be adapted when changing the hostname, for example:

```
127.0.1.1   idb-eth-melkadida-583
```

**Comment by fheslouin** [comment]
Done in https://github.com/ideascube/ansiblecube/blob/master/roles/hostapd/templates/hosts.j2
