### ISSUE TITLE
Rotate uwsgi logfile

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ansiblecube#14]
Everything is in the title

**Comment by letompouce** [comment]
The `uwsgi` package in Debian ships with [a script for `logrotate`](https://sources.debian.net/src/uwsgi/2.0.7-1/debian/uwsgi.logrotate/), and since the `ideascube` package dependencies now pulls `uwsgi` from Debian, I'd say this issue doesn't exist anymore.
