### ISSUE TITLE
git repository gets corrupted

### ISSUE THREAD

**Issue by swbsf** [ideascube/ansiblecube#148]
kb-mdg-faf-249 /var/lib/ansible/local # git status
fatal: Not a git repository (or any of the parent directories): .git

This is not really an isolated issue. We should make some checks through ansible (or somewhere else, ie dispatcher?) and re-clone repo if needed.

**Comment by fheslouin** [comment]
I think [the dispatcher]( https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/roles/network-manager/templates/nm-dispatcher.j2) script would be a great place to add this feature, this is not git related nor ansible, it is only bash script, it will be always executed.

I'll recommend to simply delete `/var/lib/ansible/local` if the git folder is corrupted

**Comment by bochecha** [comment]
What actually is the "corruption"?

IIRC @fheslouin you've had issues in the past where it was the `HEAD` file (somewhere in `.git/`) which was just empty for no reason. Is that the same thing you're seeing here @swbsf?

**Comment by fheslouin** [comment]
Yes same thing happened here

**Comment by bochecha** [comment]
Ok, so I'm starting to wonder something...

We have the `Head` file which sometimes turns out inexplicably empty... And the same happens to Ideascube's `staticfiles.json` manifest.

Am I the only one wondering if the two could be symptoms of the same underlying issue?

@mgautierfr what do you think?

**Comment by mgautierfr** [comment]
Definitively.

I never heard of a `HEAD` file being empty elsewhere than BSF boxes and we spend a looot of time on looking what could empty `staticfiles.json` also.

Both symptoms are the same, they are on two different (well used) projects, and we are the only ones to have them. It is probable that we have something wrong on our side :/

**Comment by bochecha** [comment]
I'm thinking something at the FS layer (maybe a driver bug or something like that) which causes files to not actually be written to disk when they really should be. (fsync or somethinglike that)

Do we see these "empty files" problems on KB? IDB? Both?

**Comment by fheslouin** [comment]
The HEAD file does not exactly get empty, it turn corrupted in some situation.
I have seen that on old KoomBook version in "some situation" but I can not explain why it happened though. It might be linked to a FS issue.

`staticfiles.json` turned empty just recently so I don't think we have to link both.

**Comment by bochecha** [comment]
> The HEAD file does not exactly get empty, it turn corrupted in some situation.

What is the corruption you observe? Can you define "some situation"?
