### ISSUE TITLE
tinc-dynamic handler is _always_ failing.

### ISSUE THREAD

**Issue by swbsf** [ideascube/ansiblecube#149]
RUNNING HANDLER [tinc-dynamic : Announce MAC] **********************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/var/lib/ansible/local/roles/tinc-dynamic/handlers/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#\n- name: Announce MAC\n  ^ here\n"}
...ignoring

**Comment by letompouce** [comment]
"fixed" by b590686a4c40e99db9d1e2732a9ecbcad38aea3c ?

**Comment by swbsf** [comment]
Indeed.
