### ISSUE TITLE
Kiwix and ZIM managment

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ansiblecube#16]
Currently we have to use the --library parameter in the start-up script in order to read different ZIM file.
`--library` call a `library.xml` file which contain a list of ZIM file in an XML format. This file has to be built with a binary that does not exist for ARM proc. This is not flexible at all and we have to find a new way of using Kiwix and ZIM file. 

For instance, we can call directly a ZIM file with `kiwix-serve` but in this case we have as much kiwix-server proc as we call ZIM file which is not really optimised

**Comment by kelson42** [comment]
All the stuff to build the library.xml file is here http://download.kiwix.org/bin/kiwix-server-arm.tar.bz2.
