### ISSUE TITLE
Install the RFI branding

### ISSUE THREAD

**Issue by bochecha** [ideascube/ansiblecube#167]
If you don't, the default Ideascube branding will be used, but I assume RFI will want their own branding.

Your playbook will need to install the following files:

* `/usr/share/ideascube/static/branding/header-logo.png`
* `/usr/share/ideascube/static/branding/favicon.png`

This is similar to what you already do for Koombook and Ideasbox branding.

**Comment by fheslouin** [comment]
Done here : https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/roles/ideascube/tasks/branding.yml
