### ISSUE TITLE
Set the IDEASCUBE_ID

### ISSUE THREAD

**Issue by bochecha** [ideascube/ansiblecube#169]
With the next package (this is wrong in irfi_1.0~beta1), you should be able to set this in ansiblecube, in the `/etc/default/ideascube` file as usual.

The package will also already include a configuration file which should work, named `kb_cod_rfi.py`, so the IDEASCUBE_ID should be set to `kb-cod-rfi`, as we discussed previously.

**Comment by fheslouin** [comment]
Done here : https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/roles/ideascube/tasks/ideascube.yml#L111
