### ISSUE TITLE
Adapt to the ideascube packaging changes

### ISSUE THREAD

**Issue by bochecha** [ideascube/ansiblecube#17]
I'm working on some changes in the ideascube packaging. Mostly adding to the package some stuff we're doing here.

It's not all done yet, I'm still working on it.

However, when that's done, we'll be able to simplify the ansible tasks to install ideascube.

I'm just opening this issue to remind myself it needs to be done.

**Comment by bochecha** [comment]
The packaging changes are now in: https://github.com/ideascube/ideascube/pull/272

Once that's merged, we can start removing stuff from here, since the package already does them. :smile:

**Comment by yohanboniface** [comment]
ideascube/ideascube#272 is now merged :)
