### ISSUE TITLE
uwsgi should be installed using apt-get instead of pip

### ISSUE THREAD

**Issue by letompouce** [ideascube/ansiblecube#18]
Do not perform any system-wide pip installs :)

**Comment by letompouce** [comment]
`pip uninstall uwsgi` seems to not remove anything, the binary is still in `/usr/local/bin/uwsgi` and runs fine.

While pointing systemd to `/usr/bin/uwsgi` does the trick, having two installations of uwsgi might have side effects that need to be investigated further...

**Comment by yohanboniface** [comment]
Actually, uwsgi.service is now installed by ideascube deb itself, so I think it can be totally removed from here, cf #17
