### ISSUE TITLE
Adds some lock feature to the Network-Manager if-up script.

### ISSUE THREAD

**Issue by letompouce** [ideascube/ansiblecube#20]
`/etc/NetworkManager/dispatcher.d/ansiblePullUpdate` should have some locking mechanism, so it won't run multiple times should its networking get plugged/unplugged/plugged/unplugged{1,}.

**Comment by fheslouin** [comment]
Done in https://github.com/ideascube/ansiblecube/commit/5ba7989e376a8ffbe310117b070c91d04910191f#diff-427a4d0e2ca3594cf6af373b68c994fb
