### ISSUE TITLE
Usefull debug tools

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ansiblecube#22]
When debugging servers, I often use (and thus install) httpie and elinks. Maybe we should provide them by default?

**Comment by letompouce** [comment]
The idea would be to keep the package list as little as possible, still preinstalling some debug/troubleshooting tools for when we don't have any internet connection.

Let's build a list!
- mtr-tiny
- libwww-perl

**Comment by fheslouin** [comment]
I feel like elinks, libwww-perl and httpie have the same goal. Can we choose one to use, elinks would be the easiest to use I think. 

+1 pour mtr-tiny

I will add tmux as well

**Comment by letompouce** [comment]
`libwww-perl` brings more than a web browser:

```
/usr/bin/GET
/usr/bin/HEAD
/usr/bin/POST
```

**Comment by letompouce** [comment]
WIP -- https://github.com/ideascube/ansiblecube/tree/issue-22-debugtools

**Comment by letompouce** [comment]
What a list! :D
