### ISSUE TITLE
Restart nginx and uwsgi when installing ideascube

### ISSUE THREAD

**Issue by bochecha** [ideascube/ansiblecube#28]
Currently, the ideascube package always restarts uwsgi and nginx in its `postinst` script, at initial install and update.

This is going away (see https://github.com/ideascube/ideascube/pull/341), because:
- we will set up uwsgi so that it automatically restarts on ideascube updates
- nginx pretty much never needs to be restarted on ideascube updates

This only leaves the initial install case. And it really shouldn't be the business of a given package to restart services provided in other packages.

Therefore, we should do this in ansiblecube: after installing ideascube for the first time, restart nginx and uwsgi.

**Comment by bochecha** [comment]
Note that this could be done ASAP, no need to wait for the https://github.com/ideascube/ideascube/pull/341 to be merged.

**Comment by fheslouin** [comment]
Done in 110135c65e7cba6a534440c80ed4aa75eabc3df1
