### ISSUE TITLE
Enhance the log rotation within logrotate

### ISSUE THREAD

**Issue by letompouce** [ideascube/ansiblecube#37]
`logrotate(1)` handles the logs rotation with a default configuration. Logs are named like `access.log`, `access.log.1`, `access.log.2.gz` and so on. These files are rsync'ed every time the server/koombook gets connected to internet.

Issue 1: Whenever the log rotation occurs, `access.log.2.gz` is renamed to `access.log.3.gz` ; the rsync job downloads this file again, which is useless since it was only renamed.

Issue 2 : the log rotation trashes the oldest logs. So, we only have a few days/weeks of logs, which doesn't help when it comes to debug something that happened some time ago, or wehenever we wanna learn more about the contents usage.

Solution: configure `logrotate(1)` to use the `dateeext` directive, so logs are named like `access.log-20160912`. This way, the rsync job will not download anything it already did, and it won't replace any file on the "central server" anymore, giving us a longer timespan of logs to deal with.

**Comment by fheslouin** [comment]
good point ! 
Can we establish a list of service to logrotate this way ? 
- nginx
- uwsgi
- ansible-pull.log
- etc.
  Should we for instance configure logrotate that way for all logs in /var/log...

**Comment by letompouce** [comment]
I think we should enable it globally.

I was pretty sure I did this a long time ago but I can't find anything right now... First day back from holidays might be suboptimal for mindgreps!

**Comment by letompouce** [comment]
Found it in a test VM at my home lab :-|
