### ISSUE TITLE
The installer script should write down the generated command line

### ISSUE THREAD

**Issue by letompouce** [ideascube/ansiblecube#59]
`buildMyCube.sh` is a wrapper that builds the ansible-playbook command line that installs the server at the very beginning.

The generated commandline should be written down somewhere so we can refer to it later.

It might be handy to make it an ansible fact, so we can either get it from the `logs` role or by simply `cat`'ing the facts file.

**Comment by fheslouin** [comment]
The command line is currently written in ansible-pull.log, see : https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/buildMyCube.sh#L354-L356

I think this is enough, do you ?

Otherwise we can go further and write it down in a fact file, but I don't know if it worth it

**Comment by fheslouin** [comment]
Fixed here 2c3230cd02def99776dbd53d2ffff8584a1e974d

**Comment by fheslouin** [comment]
Done
