### ISSUE TITLE
The ideascube and root passwords should not be changed when not managed by BSF.

### ISSUE THREAD

**Issue by letompouce** [ideascube/ansiblecube#62]
The commit b3dc3b7e takes care of people outside from BSF, by not changing the superstrong l33t password they did set up at the Debian install stage.

Infortunately, our [preseedcube setup](https://github.com/ideascube/preseedcube/blob/master/preseed-ideascube.cfg#L72-L79) preseedcube does set a temporary password.

Both behaviours are wanted:
- we dun change ur own passwurd
- we find it easier to type `root` as a password with a french keyboard and a US localized system.

The commit mentioned above replaced `managed_by_bsf` by `update_password=on_create` ; which honors the first bullet point but kills the second one.

We may have this user creation splitted on two tasks ; the first one is the actual one, the (short) second one would change the password `when: managed_by_bsf`. This way, we don't change external people passwords, but we don't ship servers with `root`/`root` credentials anymore.

Florian was brave enough to volunteer for such a change. Kudos to him.

**Comment by fheslouin** [comment]
Fix by 4f8e4350e194cd17216a7b3365fcdc2ed6a2ac26
