### ISSUE TITLE
Use a captive portal to ease access to ideascube.lan or koombook.lan

### ISSUE THREAD

**Issue by swbsf** [ideascube/ansiblecube#67]
Many users are connecting through their own device, thus don't know how to connect to our server.
Second, using .lan extension is chromium address bar will launch a google search instead of connecting to the server (need to explicitly type http:// -_-).
Using a captive portal forcing first connection to ideascube.lan would be a nice solution. But, notice that only first connection must be redirected. After some talking, best way seems to use iptables DNAT to redirect and then, when first connection is made, add source MAC address to an iptables white list.
Using conntrack may be a nice solution to keep white list up to date, as we'd like user to go back to ideascube.lan if browser is closed and reopened again.

**Comment by fheslouin** [comment]
In progress PR #72

**Comment by fheslouin** [comment]
PR #72 has been merged
