### ISSUE TITLE
Periodically clean leftover files

### ISSUE THREAD

**Issue by bochecha** [ideascube/ansiblecube#68]
With ideascube/ideascube#704 we now have a new command:

```
$ ideascube clean leftover-files
```

Running this will remove all the stale mediacenter files which were associated to medias, but aren't any more. (either because the media was removed, or updated to a new file)

We probably want to set up a systemd timer or something to run this command periodically and reclaim disk space.

It will be available in ideascube 0.20.0.

**Comment by fheslouin** [comment]
PR #76 has been open for review

**Comment by fheslouin** [comment]
Fixed 1b8c043
