### ISSUE TITLE
Ideasbox logo is outdated

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ansiblecube#70]
We have a [new logo for ideascube](https://github.com/ideascube/ideascube/issues/302) since 3 or 4 months but all the server prepared are still using the old logo > 

Marseille Acelem : ![image](https://cloud.githubusercontent.com/assets/4816690/22467769/2ce6accc-e7c6-11e6-8342-4ee53398a2d8.png)

I guess this is an ansible issue rather than an ideascube issue. correct me if I'm wrong.

**Comment by fheslouin** [comment]
The ideascube logo is used when we do not specify if the device is an ideasbox or a koombook.

In that case it is correct to have the ideasbox logo instead of ideascube logo as the server is an ideasbox. 

Am I correct ?

**Comment by bochecha** [comment]
Yes.
