### ISSUE TITLE
Import medias using --dry-run

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ansiblecube#71]
There is a bug in ideascube: we cant delete all medias from the mediacenter with a batch command. So we can't afford to import medias without using the --dry-run option of the import_media command. When we'll have the possibility to erase media, we will be able not to use --dry-run. Even if I rezally think that we should not ansible medias import.

**Comment by mgautierfr** [comment]
Related to ideascube/ideascube#685

**Comment by letompouce** [comment]
This is an ideascube related issue, not an ansiblecube one.
