### ISSUE TITLE
incoherent hostname and hosts

### ISSUE THREAD

**Issue by gui1117** [ideascube/ansiblecube#75]
when deployed with ideascubeName=idb_fr:

/etc/hostname
```
idb-fr-44
```

/etc/hosts
```
127.0.0.1       localhost idb_fr_44 koombook.lan
127.0.1.1       debian
192.168.2.1 koombook.lan bsfcampus.koombook.lan
```

then sudo claims: `sudo: unable to resolve host idb-fr-44` even if it does the job.

roles to blame: 
./hostapd/templates/hosts.j2:1:127.0.0.1	localhost {{ ideascubeName }} {{ hostname }}

but maybe also:
./rename_device/templates/dnsmasq.conf.j2:6:address=/{{ ideascubeName }}/{{ hotspotip }}
./rename_device/templates/hosts.j2:1:127.0.0.1	localhost {{ ideascubeName }} {{ hostname }}
./dnsmasq/templates/dnsmasq.conf.j2:6:address=/{{ ideascubeName }}/{{ hotspotip }}

**Comment by fheslouin** [comment]
Indeed, we might have some incoherent name on this branch.

Actually, this branch is outdated and we are not using it anymore for deployment, only old device rely on this one at the moment and we are trying to migrate them to our new branch "oneUpdateFile". 

I point you out directly to the right procedure to configure a new device : https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/README.md
