### ISSUE TITLE
buildmycube -m option default configuration improvements : default cards

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ansiblecube#79]
I just install ideascube on a raspberry pi using buildmycube with th -m option set to false <moment_americain> which is soooo easy and sooo awesome btw </moment_americain>. 

I said to buildmycube that I did not want the khan academy and I was not asked about the blog. Buildmycube installed the khan academy card (with nothing behind it) and the blog card. Whicch I did not want.

**Comment by fheslouin** [comment]
We have to wait for Ideascube to be able to automatically show or hide those cards

**Comment by letompouce** [comment]
These cards are defined from ideascube, `BUILTIN_APP_CARDS` and `EXTRA_APP_CARDS`. Having ansiblecube touch anything there is a no-go :)
