### ISSUE TITLE
 buildmycube -m option default configuration improvements : open wifi network

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ansiblecube#80]
A weird problem after a 'buildmycube -m false' (meaning I don't want BSF to sneak in my device) is the wifi network : it is closed by default and nobody gave me the password. The wifi network when using the -m false setup should be open. 

I think the wifi network should always be open no matter the -m option value. But this one is not my call.

**Comment by fheslouin** [comment]
This commit does the job ade9a93af817ac153623864cd061b67675bfde49 and can be merged in oneUpdateFile.

* We have to know that wifi AP will be open for everybody by default
* We will have to use `--wifi-pwd` to set a password and thus lock the wifi AP

**Comment by fheslouin** [comment]
Done #82
