### ISSUE TITLE
Forward eth0 to eth1

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ansiblecube#9]
I found myself needing to connect the two Ethiopian servers in serie in order to copy some content from one server to another, while being on the Internet for other works.

So it would be could if eth1 was forwarded to eth0, so we can connect to a server with Ethernet cable and have Internet, AND connect one server to the other when we have two of them ;)

**Comment by letompouce** [comment]
Note that newest servers now have two Wifi interfaces and a single ethernet interface.

**Comment by fheslouin** [comment]
I'm not sure it is needed anymore.This was useful in some installation/configuration server case.

**Comment by letompouce** [comment]
I'm more enclined to think that the need will occur again. Anyway, if it is not used, it doesn't hurt ; whenever it is needed, people will be glad we are such long-sighting over their needs :-)

**Comment by fheslouin** [comment]
New IdeasBox server swap eth1 for a wifi interface. The KoomBook has only one Ethernet interface. 
I'm closing the issue as this is not needed anymore.
