### ISSUE TITLE
builmycube dialog not scriptable anymore

### ISSUE THREAD

**Issue by swbsf** [ideascube/ansiblecube#94]
Seems like, because of new dialog boxes, scripts aren't able to get buildMyCube's exit codes. Especially this one : https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/buildMyCube.sh#L411-L412

**Comment by fheslouin** [comment]
Done here https://github.com/ideascube/ansiblecube/commit/23ccf917cb6b24fc41e2da2eb111db99b77a4502
