### ISSUE TITLE
Cannot detect installed version of ideascube

### ISSUE THREAD

**Issue by swbsf** [ideascube/ansiblecube#99]
Who's to blame : 
https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/roles/ideascube/tasks/ideascube.yml#L14

With LANG=C, on french OS "Installé" is written "Install?", and therefore the awk command fails.
Two options, either we keep LANG=C and ask awk to match on : 
`awk ' $1~/Install|Candidat/`

Or simply remove LANG=C.

**Comment by bochecha** [comment]
Always use a UTF-8 locale.

In this case, `LANG=C.UTF-8` should do the trick.

**Comment by swbsf** [comment]
Thanks for the tip, will try this.

**Comment by fheslouin** [comment]
Fixed here https://github.com/ideascube/ansiblecube/commit/68836d9835337c51f46159bc82cdd63479d7feba#diff-50c4a7c12e035c3a6f9d2b9eb04095a1R14
